### ISSUE TITLE
Python Examples of Services with Protobuf

### ISSUE THREAD

**Issue by JeremyBYU** [continental/ecal#39]
There seems to be only one example of using the eCAL python wrapper with Services.  However it is only passing strings (looks like its encoding a string as ascii bytes).  It would be nice if there was an example using Protobuf as we have for Publish and Subscribe. 

My guess, not sure, is that we currently have to manually serialize our Protobuff request objects as bytes and then on the receiving end deserialize them back.  Similarly with the response object.

**Comment by JeremyBYU** [comment]
Also I have a separate issue: the current python services example [here](https://github.com/continental/ecal/blob/master/samples/python/minimal_service/minimal_service.py) does not work on my system.  It errors out at:

```
(realsense) ➜  minimal_service git:(master) python minimal_service.py
eCAL v5.5.1-6-g8c81ab1 (17.12.2019)

'DemoService' method 'foo' requested with : b'hello foo 1'
Fatal Python error: PyEval_SaveThread: NULL tstate

Thread 0x00007fd44d7a3740 (most recent call first):
  File "/home/jeremy/Documents/UMICH/Research/ecal/build/python/ecal/core/core.py", line 502 in client_call_method
  File "/home/jeremy/Documents/UMICH/Research/ecal/build/python/ecal/core/service.py", line 116 in call_method
  File "minimal_service.py", line 76 in main
  File "minimal_service.py", line 96 in <module>
[1]    4244 abort (core dumped)  python minimal_service.py

```

In addition I have broken up this example into two seperate files and processes, one for the server and one for the client.  It seems to be the server code that causes the error after the client calls a method in a seperate process:

Environment:
Ubuntu 18.04
Linux Kernel 5.3
Python 3.6

**Comment by rex-schilasky** [comment]
Thank you for the issue report. We can reproduce this and will fix it asap.

**Comment by rex-schilasky** [comment]
Should be fixed now. Please recheck it.

**Comment by JeremyBYU** [comment]
So the example, `minimal_service` now works. However when I split up the server and client code I still get an error. Below is for a reproduction:

**Server**

```python
import sys
import time

import ecal.core.core as ecal_core
import ecal.core.service as ecal_service

def main():
  # print eCAL version and date
  print("eCAL {} ({})\n".format(ecal_core.getversion(), ecal_core.getdate()))
  
  # initialize eCAL API
  ecal_core.initialize(sys.argv, "Service_Server")
  
  # set process state
  ecal_core.set_process_state(1, 1, "Healthy")

  # create server "IntegrateService"
  server = ecal_service.Server("IntegrateService")

  # define the server method "integrate_scene" function
  def intregrate_scene_callback(method_name, req_type, resp_type, request):
    print("'DemoService' method '{}' called with {}".format(method_name, request))
    return 0, bytes("thank you for calling integrate :-)", "ascii")


  # define the server methods and connect them to the callbacks
  server.add_method_callback("IntegrateScene",  "string", "string", intregrate_scene_callback)

  while ecal_core.ok():
      time.sleep(0.01)

  server.destroy()
  
  # finalize eCAL API
  ecal_core.finalize()

if __name__ == "__main__":
  main()
```

**Client**

```python
import sys
from pathlib import Path
import time

import ecal.core.core as ecal_core
from ecal.core.service import Client

def client_resp_callback(service_info, response):
    print(service_info)
    print(response)

def main():
      # initialize eCAL API
    ecal_core.initialize([], "Test_Integrate_Service")
    
    # set process state
    ecal_core.set_process_state(1, 1, "Healthy")

    client = Client("IntegrateService")

      # and add it to the client
    client.add_response_callback(client_resp_callback)
    time.sleep(2)

    while True:
        request_string = bytes("Call Integrate", "ascii")
        print(request_string)
        res = client.call_method("IntegrateScene", request_string)
        print(res)
        time.sleep(1.0)

if __name__ == "__main__":
    main()

```

**Comment by rex-schilasky** [comment]
We identified the issue finally. Please recheck and thank you again for that nice issue report.

**Comment by JeremyBYU** [comment]
I pulled from master and rebuilt. Problem is now resolved! Thanks!

I also learned how to use Protobuff with services as well. You just need to create the protobuff objects manually and then use `SerializeToString` to create a request or response, and then `ParseFromString` to interpret the bytes.

**Comment by rex-schilasky** [comment]
Feel free to fork, add your client / server python samples and create a pull request.
